all: cat.out ls.out adarsh_shell.out date.out mkDir.out rm.out
adarsh_shell.out: adarsh_shell.c
	gcc adarsh_shell.c -o adarsh_shell.out
ls.out: ls.c
	gcc ls.c -o ls.out
cat.out: cat.c
	gcc cat.c -o cat.out
date.out: date.c
	gcc date.c -o date.out
rm.out: rm.c
	gcc rm.c -o rm.out
mkDir.out: mkDir.c
	gcc mkDir.c -o mkDir.out

clean: cat.out ls.out adarsh_shell.out date.out mkDir.out rm.out
